[tool.poetry]
name = "ia"
version = "0.1.0"
description = "Aplicativos de IA"
authors = ["Fabio Freitas"]
license = "Mit"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12,<3.14"
Django = "^5.0.6"
python-dotenv = "^1.0.1"
django-crispy-forms = "^2.2"
crispy-bootstrap5 = "^2024.2"
python-decouple = "^3.8"
psycopg2 = "^2.9.9"
pandas = "^2.2.3"
openpyxl = "^3.1.5"
orjson = "^3.10.15"
langchainhub = "^0.1.21"
langgraph = "^0.3.5"
langchain = "^0.3.20"
langchain-openai = "^0.3.8"
langchain-pinecone = "^0.2.3"
langchain-community = "^0.3.19"
langchain-postgres = "^0.0.13"

[tool.poetry.group.dev.dependencies]
ipdb = "^0.13.13"
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
