# Generated by Django 5.0.6 on 2024-07-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_iris'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iris',
            name='sepal_length',
            field=models.FloatField(db_comment='flor azul'),
        ),
        migrations.AlterField(
            model_name='iris',
            name='sepal_width',
            field=models.FloatField(db_comment='flor rosa'),
        ),
    ]
